# Generated by Django 4.0.4 on 2022-05-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrecord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True, null=True)),
                ('end_data', models.DateField()),
            ],
        ),
    ]
